env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
plugins: [simple-import-sort]
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  no-empty-function: off
  no-non-null-assertion: off
  react/prop-types: off
  no-explicit-any: off
  react/react-in-jsx-scope: off
  react/display-name: off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off
